<?php namespace App\Models;


use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Tag extends Model {
	
	protected $fillable = [
		'name', 'slug'	
	];
	
	protected function boot() {
		parent::boot(); // TODO: Change the autogenerated stub
		
		/**
		 * Listen creating event
		 * Defining a uuid column
		 */
		$this->creating(function ($model) {
			$uuid = Str::uuid();			
			$model->uuid = $uuid;
		});
	}
	
	/**
	 * Overriding slug column setter
	 *
	 * @param string $value
	 */
	protected function setSlugAttribute(string $value) {
		if(isset($this->attributes['slug'])) {
			return;
		}
		
		$this->attributes['slug'] = Str::slug($value);
	}
	
	/**
	 * @return \Illuminate\Support\Collection
	 */
	public function news() {
		$tagUuids = DB::table('news_tags')
			->where('tag_uuid', $this->uuid)
			->select('news_uuid')
			->get()
			->pluck('news_uuid')
			->all();
		
		return News::query()
			->whereIn('uuid', $tagUuids)
			->get();
	}

}